name: Build and Publish Add-on

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.5.0

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "ebusd" # Replace this with your add-on directory, if needed

      - name: Debug output
        run: "echo 'Architectures: ${{ steps.info.outputs.architectures }}'"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build ${{ matrix.arch }} add-on
        # if: contains(steps.info.outputs.architectures, matrix.arch)
        uses: home-assistant/builder@2023.03.0
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data \
            --image "${{ steps.info.outputs.image }}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon